### ISSUE TITLE
Pathspec did not match any file(s) known to git

### ISSUE THREAD

**Issue by milesmatthias** [mmozuras/git-playback#8]
Not sure what the issue is here but this is what I get when running the script:

``` sh
[milesmatthias]$ git playback Case.js
error: pathspec '748caebf2e63fcb830aaca8c26f02121ae2b4767' did not match any file(s) known to git.
```

**Comment by apexpatel11** [comment]
I am getting this error everytime : 
pathspec '-A' did not match any files
Any ideas ?

**Comment by mmozuras** [comment]
@apexpatel11 hi 😄. Could you give a way to reproduce the issue? A sample repo or steps?
